version = 1

[dark]
bg = "#14171B"
bg_alt = "#1A1E23"
bg_black = "#000000"
fg = "#F2F4F6"
fg_muted = "#6E737A"
fg_soft = "#9CA0A6"
fg_disabled = "#4E5660"
accent = "#B7A2FF"
accent_secondary = "#ED8EF3"
red = "#FF5C59"
green = "#4BDE7F"
yellow = "#FFA85E"
blue = "#78AFFF"
selection = "#4D486B"
selection_black = "#403959"
selected = "#1A1E23"
border = "#1A1E23"

[black]
bg = "#000000"
bg_alt = "#0C0D0E"
bg_black = "#000000"
fg = "#F2F4F6"
fg_muted = "#6E737A"
fg_soft = "#9CA0A6"
fg_disabled = "#4E5660"
accent = "#B7A2FF"
accent_secondary = "#ED8EF3"
red = "#FF5C59"
green = "#4BDE7F"
yellow = "#FFA85E"
blue = "#78AFFF"
selection = "#403959"
selection_black = "#403959"
selected = "#0F0F10"
border = "#0F0F10"

[light]
bg = "#EBEDEF"
bg_alt = "#F4F5F6"
bg_black = "#F4F5F6"
fg = "#0D0F11"
fg_muted = "#636870"
fg_soft = "#535960"
fg_disabled = "#999FA7"
accent = "#5F3BBB"
accent_secondary = "#8C2293"
red = "#B91A25"
green = "#166534"
yellow = "#8F4400"
blue = "#0054CB"
selection = "#BAAFDD"
selection_black = "#BAAFDD"
selected = "#D2D4D7"
border = "#D2D4D7"
